texto=input()
texto=texto.replace("a","")
texto=texto.replace("e","")
texto=texto.replace("i","")
texto=texto.replace("o","")
texto=texto.replace("u","")
texto=texto.replace("A","")
texto=texto.replace("E","")
texto=texto.replace("I","")
texto=texto.replace("O","")
texto=texto.replace("U","")
texto=texto.replace(" ","")
print(texto)